FROM gaffer-quickstart-base

RUN yum install mod_ssl -y

RUN openssl req \
  -new \
  -newkey rsa:4096 \
  -days 365 \
  -nodes \
  -x509 \
  -subj "/C=UK/ST=EN/L=SF/O=Gaffer-Auth/CN=gaffer.auth" \
  -keyout gaffer.auth.pem \
  -out gaffer.auth.cert

RUN keytool -importcert \
  -trustcacerts \
  -noprompt \
  -file gaffer.auth.cert \
  -storepass placeholder \
  -keystore example.jks \
  -alias "Alias" 

COPY gafferpy-build-1.9.1-SNAPSHOT-jar-with-dependencies.jar .

