FROM gaffer-quickstart-pyspark-base

ENV SCHEMA=$GAFFER_HOME/federated/schema.json
ENV GRAPHCONFIG=$GAFFER_HOME/federated/federatedGraphconfig.json
ENV STOREPROPERTIES=$GAFFER_HOME/federated/aquariumFederated.properties
ENV UICONFIG=$GAFFER_HOME/conf/ui-config.json
ENV RESTCONFIG=$GAFFER_HOME/conf/restOptions.properties

CMD $GAFFER_HOME/bin/start_federated_store.sh --schema $SCHEMA --config $GRAPHCONFIG --store $STOREPROPERTIES --ui-config $UICONFIG --rest-config $RESTCONFIG --customops-dir $CUSTOMOPSDIR; pyspark --jars $LIBS --py-files gafferpy-build-1.8.4-SNAPSHOT-python-modules.zip --packages graphframes:graphframes:0.6.0-spark2.3-s_2.11
