FROM gaffer-quickstart-pyspark-base

RUN yum install mod_ssl -y

RUN openssl req \
  -new \
  -newkey rsa:4096 \
  -days 365 \
  -nodes \
  -x509 \
  -subj "/C=UK/ST=EN/L=SF/O=Gaffer-Auth/CN=gaffer.auth" \
  -keyout gaffer.auth.pem \
  -out gaffer.auth.cert

RUN keytool -importcert \
  -trustcacerts \
  -noprompt \
  -file gaffer.auth.cert \
  -storepass placeholder \
  -keystore example.jks \
  -alias "Alias" 

RUN openssl req \
  -new \
  -newkey rsa:4096 \
  -days 3650 \
  -nodes \
  -x509 \
  -subj "/C=UK/ST=EN/L=SF/O=Gaffer-Auth/CN=gaffer.auth" \
  -keyout gaffer.auth.key \
  -out gaffer.auth.cert

ENV SSL-Enabled=True
ENV Cert-Path="/usr/gaffer/gaffer.auth.key"
ENV Client-Id="client_id"
ENV Client-Secret="client_secret"
ENV Auth-URL=https://172.18.0.2:8443/login
ENV Validate=https://172.18.0.2:8443/oauth/token

COPY graphconfig.json .
COPY pyspark-mock-accumulo.properties .
COPY simple-schema.json .

ENV SCHEMA=/usr/gaffer/simple-schema.json
ENV STOREPROPERTIES=/usr/gaffer/pyspark-mock-accumulo.properties
ENV GRAPHCONFIG=/usr/gaffer/graphconfig.json

RUN touch application.properties

RUN echo -e 'single-service=false\ninsecure=false\nuse-ssl=true\nauth-service-url=https://localhost:8443/create_session\nssl-password=placeholder\nkeystore-location=example.jks\nprotocol=TLSv1.2\nstore-properties-path=/usr/gaffer/pyspark-mock-accumulo.properties\nschema-path=/usr/gaffer/simple-schema.json\ngraph-config-path=/usr/gaffer/graphconfig.json' >> application.properties 

RUN touch index.html

RUN echo -e "<html><head><title>Gaffer Session</title></head><body><h1>GafferPy Session Controller</h1></body></html>" >> index.html

CMD $GAFFER_HOME/bin/startup.sh --schema $SCHEMA --graphconfig $GRAPHCONFIG --storeproperties $STOREPROPERTIES --ui-config $UICONFIG --rest-config $RESTCONFIG --customops-dir $CUSTOMOPSDIR; pyspark --jars $LIBS --py-files /usr/gaffer/gafferpy-build-1.9.3-SNAPSHOT-python-modules.zip --packages graphframes:graphframes:0.6.0-spark2.3-s_2.11