FROM gaffer-quickstart-pyspark-base

RUN yum install mod_ssl -y

RUN openssl req \
  -new \
  -newkey rsa:4096 \
  -days 365 \
  -nodes \
  -x509 \
  -subj "/C=UK/ST=EN/L=SF/O=Gaffer-Auth/CN=gaffer.auth" \
  -keyout gaffer.auth.pem \
  -out gaffer.auth.cert

RUN keytool -importcert \
  -trustcacerts \
  -noprompt \
  -file gaffer.auth.cert \
  -storepass placeholder \
  -keystore example.jks \
  -alias "Alias" 


RUN touch application.properties

RUN echo -e 'single-service=false\ninsecure=false\nuse-ssl=true\nauth-service-url=https://localhost:8443/create_session\nssl-password=placeholder\nkeystore-location=example.jks\nprotocol=TLSv1.2\nstore-properties-path=/usr/gaffer/gaffer-quickstart/miniaccumulo/store.properties\nschema-path=/usr/gaffer/gaffer-quickstart/example/schema.json\ngraph-config-path=/usr/gaffer/gaffer-quickstart/example/graphconfig.json' >> application.properties 

RUN touch index.html

RUN echo -e "<html><head><title>Gaffer Session</title></head><body><h1>GafferPy Session Controller</h1></body></html>" >> index.html

CMD $GAFFER_HOME/bin/startup.sh --schema $SCHEMA --graphconfig $GRAPHCONFIG --storeproperties $STOREPROPERTIES --ui-config $UICONFIG --rest-config $RESTCONFIG --customops-dir $CUSTOMOPSDIR; java -jar gafferpy-build-1.9.3-SNAPSHOT-jar-with-dependencies.jar