name: Continuous Integration

on:
  push:
    branches:
      - gh-862-migrate-ci

jobs:
  check-all-modules-are-tested:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check all modules are tested
      run: ./cd/check_modules.sh

  system-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/uk
        key: gaffer-tools-dependencies

    - name: Setup System tests
      run: ./cd/setup_ui_system_tests.sh

    - name: Run Selenium Tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn verify -P system-test -Dwebdriver.gecko.driver=geckodriver -pl ui

    - name: Run Python tests
      working-directory: python-shell
      run: python3 -m unittest discover -s src

  npm-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
        - 10
        - 12
        - 14
        module:
        - analytics/analytics-ui
        - schema-builder/schema-builder-ui

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - run: npm install
      working-directory: ${{ matrix.module }}
    - run: npm run build
      working-directory: ${{ matrix.module }}
    - run: npm run lint
      working-directory: ${{ matrix.module }}
    - run: npm run ci-test
      working-directory: ${{ matrix.module }}

  ui-test:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/uk
        key: gaffer-tools-dependencies

    - name: Install dependents
      run: mvn -q clean install -pl :ui -Pquick -am

    - name: Run Tests
      run: xvfb-run mvn verify -pl :ui

  java-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        modules:
        - :gaffer-tools,:mini-accumulo-cluster,:schema-builder,:schema-builder-rest
        - :slider
        - :random-element-generation,:performance-testing,:performance-testing-core,:performance-testing-accumulo-store,:performance-testing-aws
        - :analytics,:analytics-functions,:analytics-operations,:analytics-rest

    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/uk
        key: gaffer-tools-dependencies

    - name: Install
      run: mvn -B -q clean install -P quick -pl ${{matrix.modules}} -am

    - name: Test
      run: mvn verify -B -P coverage -pl ${{matrix.modules}}

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
