name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
      - 'alpha-release/**'

jobs:
  check-all-modules-are-tested:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check all modules are tested
      run: ./cd/check_modules.sh

  ui-selenium-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/uk
        key: gaffer-tools-dependencies

    - name: Setup System tests
      run: ./cd/setup_ui_system_tests.sh

    - name: Run Selenium Tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn verify -P system-test -Dwebdriver.gecko.driver=geckodriver -pl ui

  python-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/uk
        key: gaffer-tools-dependencies

    - name: Start road-traffic example
      run: |
        ./ui/example/road-traffic/scripts/start.sh &
        sleep 1m

    - name: Run Python tests
      working-directory: python-shell
      run: python3 -m unittest discover -s src

  ui-jasmine-test:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/uk
        key: gaffer-tools-dependencies

    - name: Install dependencies
      run: mvn -q clean install -pl :ui -Pquick -am

    - name: Run Tests
      run: xvfb-run mvn verify -pl :ui

    - name: Cleanup xvfb pidx
      uses: bcomnes/cleanup-xvfb@v1

  java-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        modules:
        - :gaffer-tools,:mini-accumulo-cluster
        - :random-element-generation,:performance-testing,:performance-testing-core,:performance-testing-accumulo-store,:performance-testing-aws

    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/uk
        key: gaffer-tools-dependencies

    - name: Install
      run: mvn -B -q clean install -P quick -pl ${{matrix.modules}} -am

    - name: Test
      run: mvn verify -B -P coverage -pl ${{matrix.modules}}

    - name: Check Copyright Headers
      if: github.event_name == 'pull_request'
      run: mvn -B -q spotless:check -pl ${{matrix.modules}}

    - name: Upload Coverage
      uses: codecov/codecov-action@v2
