name: Full Release

on:
  milestone:
   types:
   - closed

env:
  artifactId: gaffer-tools
  MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25


jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    outputs:
      branch_name: ${{ steps.branch.outputs.branch_name }}

    steps:
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Github credentials
      run: |
        git config user.name Gaffer
        git config user.email github-actions@github.com

    - name: Set release version
      run: echo "RELEASE_VERSION=$(echo ${{ github.event.milestone.title }} | cut -c 2-)" >> $GITHUB_ENV

    - name: Set branch name
      run: echo "BRANCH_NAME=$(git branch -a | grep $RELEASE_VERSION | tail -n 1 | cut -c 18-)" >> $GITHUB_ENV

    - id: branch
      run: echo "::set-output name=branch_name::$BRANCH_NAME"

    - name: Fail if no branch found
      if: ${{ !env.BRANCH_NAME }}
      run: exit 1

    - name: Set alpha master branch
      if: ${{ startsWith( env.BRANCH_NAME , 'alpha') }}
      run: echo "MASTER_BRANCH=v2-alpha" >> $GITHUB_ENV

    - name: Set master branch
      if: ${{ !startsWith( env.BRANCH_NAME , 'alpha') }}
      run: echo "MASTER_BRANCH=master" >> $GITHUB_ENV

    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: ${{ env.MASTER_BRANCH }}
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Merge release into master
      run: |
        git checkout ${{ env.BRANCH_NAME }}
        git checkout ${{ env.MASTER_BRANCH }}
        git merge ${{ env.BRANCH_NAME }}

    - name: Push changes
      run: |
        git tag $artifactId-$RELEASE_VERSION
        git push origin $artifactId-$RELEASE_VERSION
        git push

  update-develop:
    runs-on: ubuntu-latest
    needs:
    - create-release-tag

    steps:
    - name: Set develop branch
      if: ${{ !startsWith( needs.create-release-tag.outputs.branch_name , 'alpha') }}
      run: echo "DEVELOP_BRANCH=develop" >> $GITHUB_ENV

    - name: Set v2-alpha branch
      if: ${{ startsWith( needs.create-release-tag.outputs.branch_name , 'alpha') }}
      run: echo "DEVELOP_BRANCH=v2-alpha" >> $GITHUB_ENV

    - name: Checkout develop
      uses: actions/checkout@v2
      with:
        ref: develop
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Github credentials
      run: |
        git config user.name Gaffer
        git config user.email github-actions@github.com

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Skip if alpha release
    - name: Merge release into develop
      if: ${{ !startsWith( needs.create-release-tag.outputs.branch_name , 'alpha') }}
      run: |
        git checkout ${{ needs.create-release-tag.outputs.branch_name }}
        git checkout develop
        git merge ${{ needs.create-release-tag.outputs.branch_name }} --strategy-option theirs

    - name: Update appropriate development branch
      run: |
        git checkout ${{ env.DEVELOP_BRANCH }}
        mvn release:update-versions -B
        git commit -a -m "prepare for next development iteration"
        git push

  update-github-releases:
    runs-on: ubuntu-latest
    needs:
    - create-release-tag

    steps:
    - name: Checkout Master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set version
      run: echo "RELEASE_VERSION=$(echo ${{ github.event.milestone.title }} | cut -c 2-)" >> $GITHUB_ENV

    - name: Upload notes
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.artifactId }}-${{ env.RELEASE_VERSION }}
        name: Gaffer Tools ${{ env.RELEASE_VERSION }}
        body_path: release_file.md
        prerelease: ${{ startsWith( needs.create-release-tag.outputs.branch_name , 'alpha') }}

  # Skip if alpha release
  generate-javadoc:
    runs-on: ubuntu-latest
    needs:
    - create-release-tag

    steps:
    - name: Checkout Master
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Set up Github credentials
      run: |
        git config user.name Gaffer
        git config user.email github-actions@github.com

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set version
      run: echo "RELEASE_VERSION=$(echo ${{ github.event.milestone.title }} | cut -c 2-)" >> $GITHUB_ENV

    - name: Upload Javadoc
      if: ${{ !startsWith( needs.create-release-tag.outputs.branch_name , 'alpha') }}
      run: |
        git remote set-branches --add origin gh-pages
        git pull
        mvn -q clean install -Pquick -Dskip.jar-with-dependencies=true -Dshaded.jar.phase=true
        mvn -q javadoc:javadoc -Pquick
        git checkout gh-pages
        rm -rf uk
        mv target/site/apidocs/* .
        git add .
        git commit -a -m "Updated javadoc - $RELEASE_VERSION"
        git push

  release-to-nexus:
    runs-on: ubuntu-latest
    needs:
    - create-release-tag

    steps:
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout release
      uses: actions/checkout@v2
      with:
        ref: ${{ needs.create-release-tag.outputs.branch_name }}

    - name: Decode CodeSigning key
      env:
        CODE_SIGNING_KEY: ${{ secrets.CODE_SIGNING_KEY }}
        CODE_SIGNING_IV: ${{ secrets.CODE_SIGNING_IV }}
      run: openssl aes-256-cbc -K "$CODE_SIGNING_KEY" -iv "$CODE_SIGNING_IV" -in cd/codesigning.asc.enc -out cd/codesigning.asc -d

    - name: Import CodeSigning key
      run: gpg --batch --fast-import cd/codesigning.asc

    - name: Release to Nexus
      env:
        GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSS_NEXUS_USERNAME: ${{ secrets.OSS_NEXUS_USERNAME }}
        OSS_NEXUS_PASSWORD: ${{ secrets.OSS_NEXUS_PASSWORD }}
      run: mvn deploy -P quick,ossrh-release --settings cd/mvnsettings.xml -B
